trigger:
- master
- refs/tags/*
- release/*

pr:
- master
- release/*

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU

jobs:
- job: macOS
  pool: Hosted macOS
  steps:
  - template: ci/testfx.yml

- job: Linux
  pool: Hosted Ubuntu 1604
  steps:
  - template: ci/testfx.yml

- job: Windows
  pool: Hosted VS2017
  steps:
  - template: ci/build.yml
